### PR TITLE
Add anchor menu

### PR DESCRIPTION
**Pull request by Aldwin-b**
Example of what a page could look like
There is a lot of subtitle inside bigger page, it could be interesting to add a menu that allow visitors to directly reach the anchor at the top of the page

### CODE REVIEW

**Comment by jcelerier** [comment]
yep, we can do this with the docs feature: 

https://pmarsceill.github.io/just-the-docs/docs/navigation-structure/#in-page-navigation-with-table-of-contents

can you do it in another PR ?

**Comment by jcelerier** [comment]
or amend the current commits

**Comment by Aldwin-b** [comment]
I'm going to finish to whole documentation first, and then I will add an anchor menu for each pages
    Le lundi 14 juin 2021, 18:12:49 UTC+2, Jean-Michaël Celerier ***@***.***> a écrit :  
 
 


yep, we can do this with the docs feature:

https://pmarsceill.github.io/just-the-docs/docs/navigation-structure/#in-page-navigation-with-table-of-contents

can you do it in another PR ?

**Comment by jcelerier** [comment]
Works for me, thanks !

**Pull request closed without merging**
